require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/trees", type: :request do

  # This should return the minimal set of attributes required to create a valid
  # Tree. As you add validations to Tree, be sure to
  # adjust the attributes here as well.
  # let(:valid_attributes) {
  #   skip("Add a hash of attributes valid for your model")
  # }

  # let(:invalid_attributes) {
  #   skip("Add a hash of attributes invalid for your model")
  # }

  # describe "GET /index" do
  #   it "renders a successful response" do
  #     Tree.create! valid_attributes
  #     get trees_url
  #     expect(response).to be_successful
  #   end
  # end

  # describe "GET /show" do
  #   it "renders a successful response" do
  #     tree = Tree.create! valid_attributes
  #     get tree_url(tree)
  #     expect(response).to be_successful
  #   end
  # end

  # describe "GET /new" do
  #   it "renders a successful response" do
  #     get new_tree_url
  #     expect(response).to be_successful
  #   end
  # end

  # describe "GET /edit" do
  #   it "renders a successful response" do
  #     tree = Tree.create! valid_attributes
  #     get edit_tree_url(tree)
  #     expect(response).to be_successful
  #   end
  # end

  # describe "POST /create" do
  #   context "with valid parameters" do
  #     it "creates a new Tree" do
  #       expect {
  #         post trees_url, params: { tree: valid_attributes }
  #       }.to change(Tree, :count).by(1)
  #     end

  #     it "redirects to the created tree" do
  #       post trees_url, params: { tree: valid_attributes }
  #       expect(response).to redirect_to(tree_url(Tree.last))
  #     end
  #   end

  #   context "with invalid parameters" do
  #     it "does not create a new Tree" do
  #       expect {
  #         post trees_url, params: { tree: invalid_attributes }
  #       }.to change(Tree, :count).by(0)
  #     end

  #     it "renders a successful response (i.e. to display the 'new' template)" do
  #       post trees_url, params: { tree: invalid_attributes }
  #       expect(response).to be_successful
  #     end
  #   end
  # end

  # describe "PATCH /update" do
  #   context "with valid parameters" do
  #     let(:new_attributes) {
  #       skip("Add a hash of attributes valid for your model")
  #     }

  #     it "updates the requested tree" do
  #       tree = Tree.create! valid_attributes
  #       patch tree_url(tree), params: { tree: new_attributes }
  #       tree.reload
  #       skip("Add assertions for updated state")
  #     end

  #     it "redirects to the tree" do
  #       tree = Tree.create! valid_attributes
  #       patch tree_url(tree), params: { tree: new_attributes }
  #       tree.reload
  #       expect(response).to redirect_to(tree_url(tree))
  #     end
  #   end

  #   context "with invalid parameters" do
  #     it "renders a successful response (i.e. to display the 'edit' template)" do
  #       tree = Tree.create! valid_attributes
  #       patch tree_url(tree), params: { tree: invalid_attributes }
  #       expect(response).to be_successful
  #     end
  #   end
  # end

  # describe "DELETE /destroy" do
  #   it "destroys the requested tree" do
  #     tree = Tree.create! valid_attributes
  #     expect {
  #       delete tree_url(tree)
  #     }.to change(Tree, :count).by(-1)
  #   end

  #   it "redirects to the trees list" do
  #     tree = Tree.create! valid_attributes
  #     delete tree_url(tree)
  #     expect(response).to redirect_to(trees_url)
  #   end
  # end
end
